packaging_format = 2

id = "aeneria"
name = "æneria"
description.en = "Dashboard to analyse your energy consumption data from Linky & weather"
description.fr = "Tableau de bord pour analyser votre consomation d'énergie à partir des données d'un Linky et de la météo"

version = "1.1.6~ynh4"

maintainers = ["Simon Mellerin"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://aeneria.com"
admindoc = "https://docs.aeneria.com"
code = "https://gitlab.com/aeneria/aeneria-app"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/aeneria"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    help.en = "Choose whether the app should be accessible only for your yunohost users or for everyone."
    help.fr = "Choisissez si l'application doit être accessible uniquement pour vos utilisateurs yunohost ou pour tout le monde."
    type = "group"
    default = false

[resources]
        [resources.sources.main]
        url = "https://statics.aeneria.com/aeneria-app-1.1.6.tar.gz"
        sha256 = "2923c3aee79a02154c2168537a18250abe6a3a84fd7b4a5f0309bd7ad604a98b"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, apt-transport-https, postgresql-contrib, php7.4-zip, php7.4-pgsql, php7.4-xml, php7.4-intl, php7.4-mbstring, php7.4-gd, php7.4-curl, php7.4-bcmath, php7.4-opcache"

    [resources.database]
    type = "postgresql"
