packaging_format = 2

id = "aeneria"
name = "æneria"
description.en = "Analyse your energy consumption (from Linky & Gazpar) & weather data"
description.fr = "Analyser sa consommation d'énergie (via Linky & Gazpar) avec des données météo"

version = "2.0.7~ynh1"

maintainers = ["Simon Mellerin"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://aeneria.com"
admindoc = "https://docs.aeneria.com"
code = "https://gitlab.com/aeneria/aeneria-app"
demo = "https://demo.aeneria.com"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = true

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    help.en = "Choose whether the app should be accessible only for your YunoHost users or for everyone."
    help.fr = "Choisissez si l'application doit être accessible uniquement pour vos utilisateurs YunoHost ou pour tout le monde."
    type = "group"
    default = "all_users"

[resources]
    [resources.sources.main]
    url = "https://statics.aeneria.com/aeneria-app-2.0.7.tar.gz"
    sha256 = "24f62f8ee9a7e2f8ba3ad663e95bff3be05e13fa2737eda0bb2536879214f352"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, apt-transport-https, postgresql-contrib, php8.2-zip, php8.2-pgsql, php8.2-xml, php8.2-intl, php8.2-gd, php8.2-curl, php8.2-bcmath, php8.2-opcache, php8.2-ldap"

    [resources.database]
    type = "postgresql"
