packaging_format = 2

id = "aeneria"
name = "æneria"
description.en = "Dashboard to analyse your energy consumption data from Linky, Gazpar & weather"
description.fr = "Dashboard pour analyser vos données de consommation d'énergie Linky, Gazpar et météo"

version = "2.0.3~ynh1"

maintainers = ["Simon Mellerin"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://aeneria.com"
admindoc = "https://docs.aeneria.com"
code = "https://gitlab.com/aeneria/aeneria-app"
demo = "https://demo.aeneria.com"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = true

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    help.en = "Choose whether the app should be accessible only for your YunoHost users or for everyone."
    help.fr = "Choisissez si l'application doit être accessible uniquement pour vos utilisateurs YunoHost ou pour tout le monde."
    type = "group"
    default = "all_users"

[resources]
    [resources.sources.main]
    url = "https://statics.aeneria.com/aeneria-app-2.0.6.tar.gz"
    sha256 = "a13d01d793a0268da9681bc561495e438bc34e1187921f305351f7b734867b5d"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, apt-transport-https, postgresql-contrib, php7.4-zip, php7.4-pgsql, php7.4-xml, php7.4-intl, php7.4-gd, php7.4-curl, php7.4-bcmath, php7.4-opcache"

    [resources.database]
    type = "postgresql"
