packaging_format = 2

id = "aeneria"
name = "æneria"
description.en = "Dashboard to analyse your energy consumption data from Linky, Gazpar & weather"
description.fr = "Tableau de bord pour analyser votre consomation d'énergie à partir des données d'un compteur Linky et/ou Gazpar et de la météo"

version = "2.0.3~ynh1"

maintainers = ["Simon Mellerin"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://aeneria.com"
admindoc = "https://docs.aeneria.com"
code = "https://gitlab.com/aeneria/aeneria-app"
demo = "https://demo.aeneria.com"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    help.en = "Choose whether the app should be accessible only for your yunohost users or for everyone."
    help.fr = "Choisissez si l'application doit être accessible uniquement pour vos utilisateurs yunohost ou pour tout le monde."
    type = "group"
    default = false

[resources]
    [resources.sources.main]
    url = "https://statics.aeneria.com/aeneria-app-2.0.3.tar.gz"
    sha256 = "98322ac8074df007328e66cb9a5561e7e9bbbd8fefba5ef6a14cff54507e85c6"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, apt-transport-https, postgresql-contrib, php8.2-zip, php8.2-pgsql, php8.2-xml, php8.2-intl, php8.2-gd, php8.2-curl, php8.2-bcmath, php8.2-opcache"

    [resources.database]
    type = "postgresql"
