#!/bin/bash
app=APPNAMETOCHANGE

# Source YunoHost helpers
source /usr/share/yunohost/helpers
source /etc/yunohost/apps/$app/scripts/ynh_exec_as

# Retrieve arguments
username=$1
mail=$2
password=$3 # Clear password
firstname=$4
lastname=$5
final_path=$(ynh_app_setting_get "$app" final_path)

# Deactivate the user in Pilea
cd "$final_path" && ynh_exec_as $app php7.3 bin/console aeneria:user:deactivate "$mail" -n